title: St. David's Reformed Church
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: https://saintdavids.seththoburn.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
google_maps_embed_url: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d14628.712313368676!2d-95.61977666767471!3d30.096573778275264!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86472c5b2752c10f%3A0x6fd79d474258dd19!2sTomball+Community+Center!5e0!3m2!1sen!2sus!4v1562114698558!5m2!1sen!2sus
page_gen:
- index_files: 'False'
  data: sermons
  template: sermon
  name_expr: record['date'].to_s + "-" + Utils.slugify(record['title'])
